name: Quality checks 👌🧪

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

on:
  pull_request:
    paths-ignore:
      - '**/*.md'
  merge_group:
  schedule:
    - cron: 30 7 * * 6
  workflow_dispatch:

jobs:
  dependency-review:
    name: Vulnerable dependencies 🔎
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4.1.4
        with:
          show-progress: false

      - name: Scan
        uses: actions/dependency-review-action@v4.2.5
        with:
          ## Workaround from https://github.com/actions/dependency-review-action/issues/456
          ## TODO: Remove when necessary
          base-ref: ${{ github.event.pull_request.base.sha || 'master' }}
          head-ref: ${{ github.event.pull_request.head.sha || github.ref }}

  lint:
    name: Lint 🔬
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend

    steps:
      - name: Checkout ⬇️
        uses: actions/checkout@v4.1.4
        with:
          show-progress: false

      - name: Setup node environment ⚙️
        uses: actions/setup-node@v4.0.2
        with:
          node-version: 20
          check-latest: true

      - name: Install dependencies 📦
        run: npm ci --no-audit

      - name: Run linter ✏️
        run: npm run lint

  typecheck:
    name: Typecheck 🈯
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend

    steps:
      - name: Checkout ⬇️
        uses: actions/checkout@v4.1.4
        with:
          show-progress: false

      - name: Setup node environment ⚙️
        uses: actions/setup-node@v4.0.2
        with:
          node-version: 20
          check-latest: true

      - name: Install dependencies 📦
        run: npm ci --no-audit

      - name: Run typecheck 📖
        run: npm run typecheck

  build:
    name: Build 🏗️
    uses: ./.github/workflows/package.yml
    with:
      commit: ${{ github.event_name == 'pull_request' && github.sha || github.run_id }}

  pr_context:
    name: Save PR context as artifact
    if: ${{ always() && !cancelled() && github.event_name == 'pull_request' }}
    runs-on: ubuntu-latest
    needs:
      - dependency-review
      - lint
      - typecheck
      - build

    steps:
      - name: Save PR context
        env:
          PR_NUMBER: ${{ github.event.number }}
          PR_SHA: ${{ github.sha }}
        run: |
          echo $PR_NUMBER > PR_number
          echo $PR_SHA > PR_sha

      - name: Upload PR number as artifact
        uses: actions/upload-artifact@v4.3.3
        with:
          compression-level: 0
          name: PR_context
          path: |
            PR_number
            PR_sha

  conventional_commits:
    name: Conventional commits check 💬
    if: ${{ github.event_name == 'pull_request' || github.event_name == 'merge_group' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout ⬇️
        uses: actions/checkout@v4.1.4
        with:
          show-progress: false

      - name: Check if all commits comply with the specification
        uses: webiny/action-conventional-commits@v1.3.0
